name: _error
timestamp: 1489040701
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1483062480
positions: {  }
sections:
  header: Header
  navigation: Navigation
  above-slideshow: Above-slideshow
  slideshow: Slideshow
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-8583: 'Custom HTML'
    custom-4993: 'Custom HTML'
    custom-8441: 'Custom HTML'
    custom-4182: 'Custom HTML'
    custom-2936: 'Custom HTML'
    custom-6561: 'Custom HTML'
    custom-4071: 'Custom HTML'
  logo:
    logo-4770: 'Logo / Image'
    logo-7765: 'Logo / Image'
  spacer:
    spacer-2695: Spacer
  menu:
    menu-3291: Menu
  branding:
    branding-6627: Branding
  social:
    social-1417: Social
  totop:
    totop-1248: 'To Top'
  mobile-menu:
    mobile-menu-5384: Mobile-menu
inherit:
  default:
    header: header
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    logo-4770: logo-5575
    logo-7765: logo-9608
    spacer-2695: spacer-3650
    custom-4993: custom-2399
    menu-3291: menu-7668
    custom-8441: custom-9609
    custom-4182: custom-2410
    custom-2936: custom-6963
    custom-6561: custom-1285
    custom-4071: custom-5076
    branding-6627: branding-2819
    social-1417: social-3954
    totop-1248: totop-1065
    mobile-menu-5384: mobile-menu-5697
  _error:
    mainbar: mainbar
    sidebar: sidebar
