version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1483062480
layout:
  header: {  }
  navigation: {  }
  /above-slideshow/: {  }
  /slideshow/:
    -
      - custom-8583
  /container-main/:
    -
      -
        'aside 25': {  }
      -
        'mainbar 50': {  }
      -
        'sidebar 25': {  }
  footer: {  }
  offcanvas: {  }
structure:
  header:
    inherit:
      outline: default
      include:
        - attributes
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  above-slideshow:
    type: section
    attributes:
      boxed: ''
  slideshow:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
    inherit:
      outline: _error
      include:
        - attributes
        - block
        - children
  sidebar:
    type: section
    subtype: aside
    inherit:
      outline: _error
      include:
        - attributes
        - block
        - children
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - children
        - attributes
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  custom-8583:
    title: 'Custom HTML'
    attributes:
      html: "<h2 class=\"g-title\">We are sorry!</h2>\n<p>Gantry 5 provides a custom error page for you to configure with either positions, particles or a combination of both, as well as styling.</p>"
