version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1483518089
layout:
  /header/:
    -
      - 'logo-9608 15'
      - 'spacer-7683 35'
      - 'custom-2399 50'
  /navigation/:
    -
      - menu-6409
  /above-slideshow/:
    -
      - 'position-position-8391 75'
      - 'social-4869 25'
  /slideshow/:
    -
      - position-position-7192
  /container-main/:
    -
      -
        'aside 25':
          -
            - position-position-4734
      -
        'mainbar 50':
          -
            - system-content-1587
      -
        'sidebar 25':
          -
            - position-position-3949
  /footer/:
    -
      - 'custom-9609 25'
      - 'custom-2410 17'
      - 'custom-6963 17'
      - 'custom-1285 17'
      - 'custom-5076 24'
    -
      - 'branding-2819 70'
      - 'social-3954 30'
  /offcanvas/:
    -
      - mobile-menu-5697
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: '1'
      class: ''
  above-slideshow:
    type: section
    attributes:
      boxed: ''
  slideshow:
    type: section
    attributes:
      boxed: ''
  aside:
    attributes:
      class: ''
    block:
      fixed: '1'
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: '0'
      class: ''
  offcanvas:
    attributes:
      boxed: ''
content:
  logo-9608:
    title: 'Logo / Image'
  custom-2399:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"top-menu\">\n    <ul class=\"nav menu\">\n        <li><a href=\"#\">TRANDING</a></li>\n        <li><a href=\"#\">ONLINE</a></li>\n        <li><a href=\"#\">BOOK</a></li>\n        <li><a href=\"#\">EVENTS</a></li>\n        <li><a href=\"#\">ALUMNI</a></li>\n    </ul>\n</div>\n"
  position-position-8391:
    title: 'Module Position'
    attributes:
      key: hot-event
  social-4869:
    attributes:
      items:
        -
          icon: 'fa fa-twitter fa-fw'
          text: ''
          link: 'http://www.twitter.com/joomlead'
          name: Twitter
        -
          icon: 'fa fa-facebook fa-fw'
          text: ''
          link: 'http://www.facebook.com/joomlead'
          name: Facebook
        -
          icon: 'fa fa-google-plus fa-fw'
          text: ''
          link: 'https://plus.google.com/+joomlead'
          name: Google+
        -
          icon: 'fa fa-instagram'
          text: ''
          link: '#'
          name: Instagram
        -
          icon: 'fa fa-pinterest'
          text: ''
          link: '#'
          name: Pinterest
  position-position-7192:
    title: 'Module Position'
    attributes:
      key: slideshow
  position-position-4734:
    title: Aside
    attributes:
      key: aside
  position-position-3949:
    title: Sidebar
    attributes:
      key: sidebar
  custom-9609:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"jl-ft-about\" style=\"text-align: left\">\n\t<div class=\"jl-heading\">\n      <img src=\"templates\\jl_learnmate_free\\images\\logo\\logo.png\" alt=\"\" />\n  </div>\n</div>"
  custom-2410:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"jl-custom-ft uk-grid\">\n  <div class=\"jl-custom-title uk-width-1-1\">\n    <h3>INFORMATION</h3>\n  </div>\n\n    <div class=\"jl-custom-link uk-width-1-1\">\n      <a href=\"#\">Who we are </a>\n    </div>\n    <div class=\"jl-custom-link uk-width-1-1\">\n      <a href=\"#\">History </a>\n    </div>\n    <div class=\"jl-custom-link uk-width-1-1\">\n      <a href=\"#\">Facts & Figures </a>\n    </div>\n    <div class=\"jl-custom-link uk-width-1-1\">\n      <a href=\"#\">Programs </a>\n    </div>\n    <div class=\"jl-custom-link uk-width-1-1\">\n      <a href=\"#\">Mission / Vision </a>\n    </div>\n\n</div>"
  custom-6963:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"jl-custom-ft uk-grid\">\n  <div class=\"jl-custom-title uk-width-1-1\">\n    <h3>QUICK LINK</h3>\n  </div>\n\n    <div class=\"jl-custom-link uk-width-1-1\">\n      <a href=\"#\">Falcuties & Department </a>\n    </div>\n    <div class=\"jl-custom-link uk-width-1-1\">\n      <a href=\"#\">Business & Corporation </a>\n    </div>\n    <div class=\"jl-custom-link uk-width-1-1\">\n      <a href=\"#\">Events </a>\n    </div>\n    <div class=\"jl-custom-link uk-width-1-1\">\n      <a href=\"#\">Charity </a>\n    </div>\n    <div class=\"jl-custom-link uk-width-1-1\">\n      <a href=\"#\">Alumni </a>\n    </div>\n</div>"
  custom-1285:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"jl-custom-ft uk-grid\">\n  <div class=\"jl-custom-title uk-width-1-1\">\n    <h3>EXTRA LINK</h3>\n  </div>\n\n    <div class=\"jl-custom-link uk-width-1-1\">\n      <a href=\"#\">Accessibility </a>\n    </div>\n    <div class=\"jl-custom-link uk-width-1-1\">\n      <a href=\"#\">Legal </a>\n    </div>\n    <div class=\"jl-custom-link uk-width-1-1\">\n      <a href=\"#\">Sitemap </a>\n    </div>\n    <div class=\"jl-custom-link uk-width-1-1\">\n      <a href=\"#\">Terms of use </a>\n    </div>\n    <div class=\"jl-custom-link uk-width-1-1\">\n      <a href=\"#\">Privacy </a>\n    </div>\n</div>"
  custom-5076:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"jl-custom-ft uk-grid\">\n  <div class=\"jl-custom-title uk-width-1-1\">\n    <h3>CONTACT INFORMATION</h3>\n  </div>\n\n    <div class=\"jl-custom-link uk-width-1-1\">\n      <a href=\"#\">Senate House, Tyndall\nAvenue, Bristol, BS8 1TH, UK. </a>\n    </div>\n    <div class=\"jl-custom-link uk-width-1-1\">\n      <a href=\"#\">Tel: +44 (0)117 928 9000 </a>\n    </div>\n    <div class=\"jl-custom-link uk-width-1-1\">\n      <a href=\"#\">Email: demo@joomlead.com </a>\n    </div>\n\n</div>"
  branding-2819:
    attributes:
      content: 'Copyright © 2016. Powered by <a href="https://www.joomlead.com/" title="JoomLead" class="g-powered-by">JoomLead<span class="hidden-tablet"> </span></a>.All rights reserved.'
  social-3954:
    attributes:
      items:
        -
          icon: 'fa fa-twitter fa-fw'
          text: ''
          link: 'http://www.twitter.com/joomlead'
          name: Twitter
        -
          icon: 'fa fa-facebook fa-fw'
          text: ''
          link: 'http://www.facebook.com/joomlead'
          name: Facebook
        -
          icon: 'fa fa-google-plus fa-fw'
          text: ''
          link: 'https://plus.google.com/+joomlead'
          name: Google+
        -
          icon: 'fa fa-instagram'
          text: ''
          link: '#'
          name: Instagram
        -
          icon: 'fa fa-pinterest'
          text: ''
          link: '#'
          name: Pinterest
